[package]
name = "pb-rules-core"
version = "0.1.0"
edition = "2021"
authors.workspace = true
license.workspace = true
include.workspace = true

[lib]
crate-type = ["cdylib"]

[dependencies]
tracing = "0.1"
wit-bindgen = "0.41.0"
