[package]
name = "pb-cli"
version = "0.1.0"
edition = "2024"
authors.workspace = true
license.workspace = true
include.workspace = true

[dependencies]
clap = { version = "4", features = ["derive"] }
indicatif = "0.17"
