[package]
name = "pb-lang-rust"
version = "0.1.0"
edition = "2021"

authors.workspace = true
license.workspace = true
include.workspace = true

[lib]
crate-type = ["cdylib"]
path = "src/lib.rs"
name = "fib"

[dependencies]
