[package]
name = "pb-rules-sdk"
version = "0.1.0"
edition = "2024"
authors.workspace = true
license.workspace = true
include.workspace = true

[dependencies]
futures = "0.3"
pb-ore = { path = "../pb-ore" }
tracing = "0.1"
tracing-subscriber = "0.3"
wit-bindgen = "0.42"
