[package]
name = "pb-ore"
version = "0.1.0"
edition = "2021"
authors.workspace = true
license.workspace = true
include.workspace = true

[dependencies]
paste = "1"
pb-types = { path = "../pb-types" }
xxhash-rust = { version = "0.8", features = ["xxh3"] }
